### ISSUE TITLE
hardcoded references to knife.rb

### ISSUE THREAD

**Issue by mvillis** [chef-cookbooks/delivery-sugar#2]
There are a couple of references to the location of knife.rb in delivery-sugar:
[delivery_chef_server.rb](https://github.com/chef-cookbooks/delivery-sugar/blob/ea84ae14a8481fa7cbb0babfdc0f22007c0f8dd3/libraries/delivery_chef_server.rb#L193-L195)
[delivery_push_jobs_resource.rb](https://github.com/chef-cookbooks/delivery-sugar/blob/cbc4cd45738712a0e67b8c207e8798a5310a12a6/libraries/delivery_push_job_resource.rb#L32)

At the moment some server permissions means its desirable for me to be storing this config in a spot other than /var/opt/delivery/workspace/.chef but this breaks delivery-sugar.

Is offering this as an configurable location an option? Something like a chef_config attribute you could pass into the resource.

Happy to code up a PR just keen for some community guidance first up.

**Comment by afiune** [comment]
@mvillis Thank you for your feedback!! 

I think this is kinda the same issue you reported here https://github.com/chef-cookbooks/delivery-truck/issues/12 and I have answered there. I would love to know what are you trying to do so we can assist you in a better way. For instance, what are those permissions issues you mentioned? Do you have any log/output that we can see?

**Comment by mvillis** [comment]
@afiune the permissions form part of our MSB (minimum security baseline). Where we can we've been trying to align to these (especially in cases like build nodes which we expect to be quite large in number eventually).

**Comment by afiune** [comment]
Definitely I see the value on this. Thank you for explaining the idea! :smile: I will talk to the team to come with a solution for this use case. Will keep you posted!

**Comment by afiune** [comment]
@mvillis I think this change involve more that just a build-cookbook change. I am thinking in modifying the `delivery-cli` as well to be able to inherit the configuration. I will keep you posted of any change. Thanks for the patient :smile:

**Comment by afiune** [comment]
Making good progress, here is the output of the `delivery-cli` change plus the `delivery-sugar` one:
```ruby
Starting job on builder build-node-aws-2 at 2015-10-11T16:56:31+00:00.
Command: delivery job verify lint --server 10.194.15.247 --user builder --ent aws --org aws --project test-cli-sugar --for master --change-id 59f7bd94-708d-4646-8a6e-7558e0a6ecfc --branch _reviews/master/add-delivery-config/8 --git-url ssh://builder@aws@10.194.15.247:8989/aws/aws/test-cli-sugar
Chef Delivery
Loading configuration from /var/my/awesome/workspace
Starting job for test-cli-sugar verify lint
Creating workspace in /var/my/awesome/workspace/10.194.15.247/aws/aws/test-cli-sugar/master/verify/lint
Cloning repository, and merging _reviews/master/add-delivery-config/8 to master
Configuring the job
Running the job
Setting up the builder
[2015-10-11T16:56:47+00:00] WARN: Ohai::Config[:disabled_plugins] is set. Ohai::Config[:disabled_plugins] is deprecated and will be removed in future releases of ohai. Use ohai.disabled_plugins in your configuration file to configure :disabled_plugins for ohai.
Starting Chef Client, version 12.5.1
resolving cookbooks for run list: ["build-cookbook::default"]
Synchronizing Cookbooks:
  - build-cookbook (0.1.0)
  - delivery-truck (1.100.6)
  - delivery-sugar (0.3.0)
Compiling Cookbooks...
Converging 3 resources
Recipe: delivery-truck::default
  * chef_gem[chefspec] action install
    - install version 4.1.1 of package chefspec
  * chef_gem[chef-sugar] action upgrade
    - upgrade package chef-sugar from uninstalled to 3.1.1
  * chef_gem[knife-supermarket] action install (skipped due to only_if)

Running handlers:
Running handlers complete
Chef Client finished, 2/3 resources updated in 08 seconds
Running phase lint
[2015-10-11T16:56:58+00:00] WARN: Ohai::Config[:disabled_plugins] is set. Ohai::Config[:disabled_plugins] is deprecated and will be removed in future releases of ohai. Use ohai.disabled_plugins in your configuration file to configure :disabled_plugins for ohai.
Starting Chef Client, version 12.5.1
resolving cookbooks for run list: ["build-cookbook::lint"]
Synchronizing Cookbooks:
  - delivery-sugar (0.3.0)
  - delivery-truck (1.100.6)
  - build-cookbook (0.1.0)
Compiling Cookbooks...
Converging 2 resources
Recipe: delivery-truck::lint
  * execute[lint_foodcritic_test-cli-sugar] action run
    - execute foodcritic -f correctness   /var/my/awesome/workspace/10.194.15.247/aws/aws/test-cli-sugar/master/verify/lint/repo/
  * execute[lint_rubocop_test-cli-sugar] action run (skipped due to only_if)

Running handlers:
Running handlers complete
Chef Client finished, 1/2 resources updated in 01 seconds

Job ended at 2015-10-11T16:57:02+00:00 (ran in 31 seconds)
```

**Comment by afiune** [comment]
This `delivery-cli` change will help a lot! :smile: https://github.com/chef/delivery-cli/commit/d8a2a5829971f23c2c4e1f0c2c056c55463297de

Coming the change to `delivery-sugar` to adopt it! :+1:
