### ISSUE TITLE
delivery_workspace doesn't reference attributes setup by delivery_build

### ISSUE THREAD

**Issue by mjohno** [chef-cookbooks/delivery-sugar#3]
The function [delivery_workspace](https://github.com/chef-cookbooks/delivery-sugar/blob/72e156ebd79a4b57d94194cd7d9843f85c310a5f/libraries/delivery_dsl.rb#L34) checks the node attribute `node['delivery']['workspace_path']`. Where does this attribute get set? Should it be checking against `node['delivery_build']['root']` as that is what gets set in [delivery_build](https://github.com/chef-cookbooks/delivery_build/blob/master/attributes/default.rb#L23-L28)?

**Comment by afiune** [comment]
@mjohno That attribute is coming from the [delivery-cli](https://github.com/chef/delivery-cli/blob/master/src/delivery/job/dna.rs#L23) :smile:

**Comment by mjohno** [comment]
All good, thanks again @afiune
